on: [push, pull_request]
name: Go test
jobs:
  oldest:
    name: The oldest possible Go version whatever hacks needed
    runs-on: ubuntu-24.04
    steps:
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.9.4"
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Hack for ancient mod-incompatible Go versions
        run: mkdir -p /home/runner/go/src/github.com/apsystole && cp -pr . /home/runner/go/src/github.com/apsystole/log
      - name: Find
        run: find . -ls
      - name: Test
        run: go test ./...
  gcp_cloud_functions_exact_ubuntu20:
    name: Tests on GCP's exact versions per https://cloud.google.com/functions/docs/concepts/go-runtime
    strategy:
      matrix:
        go-version: ["1.13.15"]
        os: [ubuntu-20.04] # GCP actually uses 18.04, but they are unsupported on any free-tier CI.
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Test
        run: go test ./...
  gcp_cloud_functions_exact_ubuntu22:
    name: Tests on GCP's exact versions per https://cloud.google.com/functions/docs/concepts/go-runtime
    strategy:
      matrix:
        go-version: ["1.18.10", "1.19.13", "1.21.10"]
        os: [ubuntu-22.04]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Test
        run: go test ./...
  latest:
    name: Test the latest Go on the latest OSes
    strategy:
      matrix:
        go-version: ["1.x"]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Test
        run: go test ./...
